"""Database init

Revision ID: 12564635c4be
Revises: fcb782854452
Create Date: 2024-06-03 14:40:14.344170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12564635c4be'
down_revision: Union[str, None] = 'fcb782854452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_verifed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verifed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
